spring:
  application:
    name: omnicon

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.xojdoygcxxglhpquapzt&password=
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG