### 컨퍼런스 호스트 등록
POST http://localhost:8080/api/v1/videos
Content-Type: application/json

{
  "youtubeVideoId": "pCE7ibRCZEI",
  "title": "스프링 테스트 코드",
  "description": "스프링 테스트 코드 라이브러리",
  "thumbnailUrl": "thumbnailUrl",
  "conferenceToken": "",
  "speakerTokens": "",
}
