### 영상 내용 등록
POST http://localhost:8080/api/v1/videos
Content-Type: application/json

{
  "youtubeVideoId": "pCE7ibRCZEI",
  "title": "스프링 테스트 코드",
  "description": "스프링 테스트 코드 라이브러리",
  "thumbnailUrl": "thumbnailUrl",
  "conferenceToken": "b646551c-e0cf-464c-9363-be984c677c88"
}

### 영상 일반 조회
GET http://localhost:8080/api/v1/videos?keyword=테스트 코드
Content-Type: application/json

### 영상 상세 조회
GET http://localhost:8080/api/v1/videos/0260ce75-bd8f-4a98-8ff8-bf56da42a978
Content-Type: application/json